# fills boxes and Submits
from selenium import webdriver
from selenium.webdriver.common.by import By

import time

driver = webdriver.Firefox()
driver.maximize_window()
driver.get("https://demoqa.com/text-box")

username = driver.find_element(By.ID,"userName").send_keys("Tara Li")

time.sleep(2)
# driver.quit()

#------

email = driver.find_element(By.ID, "userEmail").send_keys("tests@testy.com")

time.sleep(2)
# driver.quit()

#------

currentaddress = driver.find_element(By.ID, "currentAddress").send_keys("12345 S Ave")

time.sleep(2)
# driver.quit()

#------

permaddress = driver.find_element(By.ID, "permanentAddress").send_keys("98765 N Blvd")

time.sleep(2)
# driver.quit()

#------

#click the submit button

button = driver.find_element(By.ID, "submit")
button.click()

driver.quit()

